#!/usr/bin/env -S uv run --script

import math
import random

print('''<svg width="734" height="400" xmlns="http://www.w3.org/2000/svg">
<circle cx="0" cy="400" r="400" fill="rgba(55, 55, 55, .1)" stroke="black" stroke-width="2"/>
<rect x="0" y="0" width="400" height="400" fill="none" stroke="black" stroke-width="2"/>''')

number_in = 0

for i in range(400):
    x = random.randint(0, 400)
    y = random.randint(0, 400)
    if math.pow(x, 2) + math.pow(400 - y, 2) < math.pow(400, 2):
        number_in += 1
        color = "blue"
    else:
        color = "black"

    print(f'<circle cx="{x}" cy="{y}" r="4" fill="{color}"/>')

for i in range(20):
    for j in range(20):
        if number_in > 0:
            color = "blue"
            number_in -= 1
        else:
            color = "black"

        print(f'<circle cx="{500 + 12*j}" cy="{314 - 12*i}" r="4" fill="{color}"/>')

print('</svg>')
